### ISSUE TITLE
New stores created shows up in accounts of other users

### ISSUE THREAD

**Issue by dino-bear** [DeerMarket/frontend#5]

**Comment by dino-bear** [comment]
Was fixed in this commit
https://github.com/DeerMarket/contracts/commit/8862bd66192b02cda5a57b1cfad7160e58247fb6

Needs to be deployed to production first

**Comment by hichamtloh** [comment]
yes it has been fixed

**Comment by dino-bear** [comment]
Deployed to dm7.testnet
